version: '3.5'

services:
  minio:
    image: minio/minio
    environment:
        MINIO_ROOT_USER: 'AKIAIOSFODNN7EXAMPLE' # or any user name you like , this will be used to log in to minio dashboard
        MINIO_ROOT_PASSWORD: 'wJalrXUtnFEMIK7MDENGbPxRfiCYEXAMPLEKEY'
    command: ['server', '/data', '--console-address', ':7001']
    ports:
      - 7000:7000
      - 7001:7001
    volumes:
        - minio:/data

volumes:
    minio:
        driver: local